apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clients
  template:
    metadata:
      labels:
        app: clients
    spec:
      containers:
        - name: clients
          image: 130620/microservices-clients:latest
---
apiVersion: v1
kind: Service
metadata:
  name: client-service-ip
spec:
  selector:
    app: clients
  ports:
    - name: clients
      protocol: TCP
      port: 3000 # port of nodePort
      targetPort: 3000 # targetPort of Pods, request for traffic