apiVersion: apps/v1
kind: Deployment
metadata:
  name: moderations-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moderations
  template:
    metadata:
      labels:
        app: moderations
    spec:
      containers:
        - name: moderations
          image: 130620/microservices-moderations:latest
---
apiVersion: v1
kind: Service
metadata:
  name: moderations-service
spec:
  type: NodePort
  selector:
    app: moderations
  ports:
    - name: moderations
      protocol: TCP
      port: 4003
      targetPort: 4003
