apiVersion: apps/v1
kind: Deployment
metadata:
  name: moderation-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moderations
  template:
    metadata:
      labels:
        app: moderations
    spec:
      containers:
        - name: moderations
          image: 130620/microservices-moderations:latest
---
apiVersion: v1
kind: Service
metadata:
  name: moderation-service-ip
spec:
  selector:
    app: moderations
  ports:
    - name: moderations
      protocol: TCP
      port: 4003 # port of nodePort
      targetPort: 4003 # targetPort of Pods, request for traffic