apiVersion: apps/v1
kind: Deployment
metadata:
  name: events-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: events
  template:
    metadata:
      labels:
        app: events
    spec:
      containers:
        - name: events
          image: 130620/microservices-events:latest
---
apiVersion: v1
kind: Service
metadata:
  name: events-service
spec:
  selector:
    app: events
  type: ClusterIP
  ports:
    - name: events
      protocol: TCP
      port: 4005
      targetPort: 4005
