apiVersion: apps/v1
kind: Deployment
metadata:
  name: comments
spec:
  containers:
    - image: 130620/microservices-comments
      name: comments
      ports:
        - containerPort: 4001
          protocol: TCP
